'use client'
/* eslint-disable @next/next/no-img-element */
/* eslint-disable @next/next/no-sync-scripts */
import { Inter } from "next/font/google";
import "../globals.css";
import "../../../public/bootstrap/css/bootstrap.min.css";
import Link from "next/link";
import HeaderAmin from "../layout/admin/headerAdmin";
import FooterAdmin from "../layout/admin/footerAdmin";
import Providers from "@/redux/provider";
import { usePathname } from "next/navigation";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  const pathName = usePathname();

  return (
    <html lang="en">
      <body>
      {/* <title>{metadata.title}</title> */}
        <div className="container-fluid" >
      <div className="row">
        <div className="col-md-2 p-0 collapse collapse-horizontal show" style={{minHeight: "100vh", backgroundColor: "#202124"}} id="moMenu">
          <strong className="text-center d-block p-3" style={{color: "white"}}> 
            <img src="/images/logo.png" width="80px" alt=""/>
            <br/>
            Asian-Food Admin
           </strong>
           <div className="list-group ms-2 me-2">
            <Link href="/admin" className={`list-group-item list-group-item-action ${pathName == '/admin' ? "text-bg-dark":"" }`} aria-current="true">
              Tổng Quan
            </Link>
            <Link href="/admin/order" className={`list-group-item list-group-item-action ${pathName == '/admin/order' ? "text-bg-dark":"" }`}>Đơn Hàng</Link>
            <Link href="/admin/product" className={`list-group-item list-group-item-action ${pathName == '/admin/product' ? "text-bg-dark":"" }`}>Sản Phẩm</Link>
            <Link href="/admin/category" className={`list-group-item list-group-item-action ${pathName == '/admin/category' ? "text-bg-dark":"" }`}>Danh Mục</Link>
            <Link href="/admin/user" className={`list-group-item list-group-item-action ${pathName == '/admin/user' ? "text-bg-dark":"" }`}>Tài Khoản </Link>
            <Link href="/admin/brand" className={`list-group-item list-group-item-action ${pathName == '/admin/brand' ? "text-bg-dark":"" }`}>Thương Hiệu</Link>
            <Link href="/" className="list-group-item list-group-item-action" aria-disabled="true">Quay về Trang Chủ</Link>
          </div>
        </div>
        <div className="col-md p-0">
          <nav className="navbar navbar-expand-lg bg-body-tertiary">
            <button className="btn btn-secondary ms-1" type="button" data-bs-toggle="collapse" data-bs-target="#moMenu" aria-expanded="false" aria-controls="moMenu">
              =
            </button>
            <div className="container-fluid">
              <div className="collapse navbar-collapse" id="navbarSupportedContent">
                <form className="d-flex" role="search">
                  <input className="form-control " type="search" placeholder="Search" aria-label="Search"/>
                  <button className="btn btn-outline-warning" type="submit">Search</button>
                </form>
                <ul className="navbar-nav ms-auto mb-2 me-2 mb-lg-0">
                  <li className="nav-item dropdown">
                    <a className="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Xin Chào, Anh Thư
                    </a>
                    <ul className="dropdown-menu ">
                      <li><a className="dropdown-item" href="#">Tìm rì ?</a></li>
                      <li><a className="dropdown-item" href="#">Ai biếc ?</a></li>
                      <li><hr className="dropdown-divider"/></li>
                      <li><a className="dropdown-item" href="#">Đăng Xuất</a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
        <Providers>
            {children}
        </Providers>
        {/* <FooterAdmin></FooterAdmin> */}
        </div>
      </div>
    </div>



        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="https://kit.fontawesome.com/6895c8023a.js" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"/>
      </body>
    </html>
  );
}
